import { db } from "./db";
import { products, users, promoCodes } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  console.log("🌱 Seeding database...");

  // Create admin user
  const adminEmail = "admin@zinoucha.com";
  await db.insert(users).values({
    email: adminEmail,
    firstName: "Admin",
    lastName: "Zinoucha",
    isAdmin: true,
  }).onConflictDoNothing();

  // Sample product data
  const sampleProducts = [
    // Vêtements
    {
      name: "Robe Élégante Noire",
      description: "Robe de soirée élégante en satin, parfaite pour les occasions spéciales. Coupe ajustée et flatteuse.",
      price: "12500",
      salePrice: null,
      category: "vetements",
      subcategory: "robes",
      brand: "Elegance Paris",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Noir"],
      images: ["/placeholder-dress-1.jpg"],
      stock: 15,
      featured: true,
      isNew: true,
    },
    {
      name: "Ensemble Tailleur Chic",
      description: "Tailleur deux pièces moderne et professionnel. Veste cintrée et pantalon droit pour un look sophistiqué.",
      price: "18500",
      salePrice: "15000",
      category: "vetements",
      subcategory: "ensembles",
      brand: "Career Style",
      sizes: ["S", "M", "L"],
      colors: ["Beige", "Noir", "Bleu marine"],
      images: ["/placeholder-suit-1.jpg"],
      stock: 20,
      featured: true,
      isNew: false,
    },
    {
      name: "Pull Cachemire Doux",
      description: "Pull en cachemire ultra-doux, parfait pour les journées fraîches. Matière premium et confortable.",
      price: "8900",
      salePrice: null,
      category: "vetements",
      subcategory: "hauts",
      brand: "Soft Luxury",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Rose", "Beige", "Gris"],
      images: ["/placeholder-sweater-1.jpg"],
      stock: 30,
      featured: false,
      isNew: true,
    },
    {
      name: "Jean Slim Confortable",
      description: "Jean slim stretch pour un confort optimal toute la journée. Coupe moderne et flatteuse.",
      price: "6500",
      salePrice: null,
      category: "vetements",
      subcategory: "pantalons",
      brand: "Denim Co",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Bleu", "Noir"],
      images: ["/placeholder-jeans-1.jpg"],
      stock: 40,
      featured: false,
      isNew: false,
    },
    {
      name: "Chemisier Soie Blanc",
      description: "Chemisier en soie pure, élégant et polyvalent. Parfait pour le bureau ou les sorties.",
      price: "7800",
      salePrice: "6500",
      category: "vetements",
      subcategory: "hauts",
      brand: "Silk Touch",
      sizes: ["S", "M", "L"],
      colors: ["Blanc", "Crème"],
      images: ["/placeholder-blouse-1.jpg"],
      stock: 25,
      featured: true,
      isNew: false,
    },
    {
      name: "Manteau Long Laine",
      description: "Manteau long en laine de qualité supérieure. Chaleureux et élégant pour l'hiver.",
      price: "22000",
      salePrice: null,
      category: "vetements",
      subcategory: "manteaux",
      brand: "Winter Elegance",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Camel", "Noir", "Gris"],
      images: ["/placeholder-coat-1.jpg"],
      stock: 12,
      featured: true,
      isNew: true,
    },
    {
      name: "Jupe Plissée Mi-Longue",
      description: "Jupe plissée mi-longue, style intemporel et féminin. Parfaite pour toutes les occasions.",
      price: "5500",
      salePrice: null,
      category: "vetements",
      subcategory: "jupes",
      brand: "Femme Chic",
      sizes: ["XS", "S", "M", "L"],
      colors: ["Noir", "Bordeaux", "Bleu marine"],
      images: ["/placeholder-skirt-1.jpg"],
      stock: 35,
      featured: false,
      isNew: false,
    },

    // Maquillage
    {
      name: "Palette Fards à Paupières Nude",
      description: "Palette de 12 fards nude pour un look naturel ou sophistiqué. Haute pigmentation et longue tenue.",
      price: "4500",
      salePrice: null,
      category: "maquillage",
      subcategory: "yeux",
      brand: "Beauty Pro",
      sizes: [],
      colors: ["Nude"],
      images: ["/placeholder-eyeshadow-1.jpg"],
      stock: 50,
      featured: true,
      isNew: true,
    },
    {
      name: "Rouge à Lèvres Mat Longue Tenue",
      description: "Rouge à lèvres mat à la texture veloutée. Tenue 8h sans transfert, confort optimal.",
      price: "2800",
      salePrice: null,
      category: "maquillage",
      subcategory: "lèvres",
      brand: "Lip Perfect",
      sizes: [],
      colors: ["Rouge", "Rose", "Nude", "Bordeaux"],
      images: ["/placeholder-lipstick-1.jpg"],
      stock: 80,
      featured: true,
      isNew: false,
    },
    {
      name: "Fond de Teint Fluide Naturel",
      description: "Fond de teint fluide pour un fini naturel et lumineux. Couvre les imperfections sans effet masque.",
      price: "3500",
      salePrice: "2900",
      category: "maquillage",
      subcategory: "teint",
      brand: "Skin Glow",
      sizes: [],
      colors: ["Ivoire", "Beige", "Caramel", "Chocolat"],
      images: ["/placeholder-foundation-1.jpg"],
      stock: 60,
      featured: false,
      isNew: false,
    },
    {
      name: "Mascara Volume Intense",
      description: "Mascara volumateur pour des cils XXL. Formule enrichie sans grumeaux, tenue 24h.",
      price: "2200",
      salePrice: null,
      category: "maquillage",
      subcategory: "yeux",
      brand: "Lash Beauty",
      sizes: [],
      colors: ["Noir", "Marron"],
      images: ["/placeholder-mascara-1.jpg"],
      stock: 70,
      featured: false,
      isNew: true,
    },
    {
      name: "Kit Pinceaux Maquillage Professionnel",
      description: "Ensemble de 12 pinceaux professionnels avec étui. Poils synthétiques ultra-doux.",
      price: "6800",
      salePrice: null,
      category: "maquillage",
      subcategory: "accessoires",
      brand: "Brush Master",
      sizes: [],
      colors: ["Rose Gold"],
      images: ["/placeholder-brushes-1.jpg"],
      stock: 30,
      featured: true,
      isNew: false,
    },
    {
      name: "Enlumineur Poudre Dorée",
      description: "Poudre enlumineur pour un teint éclatant. Éclat naturel et lumineux, facile à estomper.",
      price: "3200",
      salePrice: null,
      category: "maquillage",
      subcategory: "teint",
      brand: "Glow Beauty",
      sizes: [],
      colors: ["Or", "Champagne"],
      images: ["/placeholder-highlighter-1.jpg"],
      stock: 45,
      featured: false,
      isNew: true,
    },
    {
      name: "Eyeliner Liquide Noir Intense",
      description: "Eyeliner liquide ultra-précis avec applicateur fin. Noir intense, tenue waterproof 12h.",
      price: "1800",
      salePrice: null,
      category: "maquillage",
      subcategory: "yeux",
      brand: "Eye Perfect",
      sizes: [],
      colors: ["Noir"],
      images: ["/placeholder-eyeliner-1.jpg"],
      stock: 90,
      featured: false,
      isNew: false,
    },

    // Parfums
    {
      name: "Eau de Parfum Floral Oriental",
      description: "Parfum floral oriental envoûtant aux notes de jasmin, vanille et musc. Tenue longue durée.",
      price: "8500",
      salePrice: null,
      category: "parfums",
      subcategory: "femme",
      brand: "Luxe Fragrance",
      sizes: ["50ml", "100ml"],
      colors: [],
      images: ["/placeholder-perfume-1.jpg"],
      stock: 25,
      featured: true,
      isNew: true,
    },
    {
      name: "Eau de Toilette Fraîche Citrus",
      description: "Eau de toilette légère et fraîche aux notes d'agrumes et de fleurs blanches. Parfaite pour l'été.",
      price: "5500",
      salePrice: null,
      category: "parfums",
      subcategory: "femme",
      brand: "Fresh Scent",
      sizes: ["50ml", "75ml"],
      colors: [],
      images: ["/placeholder-perfume-2.jpg"],
      stock: 40,
      featured: true,
      isNew: false,
    },
    {
      name: "Parfum Intense Boisé Ambré",
      description: "Fragrance intense et sophistiquée aux notes boisées et ambrées. Pour une femme élégante.",
      price: "12000",
      salePrice: "9500",
      category: "parfums",
      subcategory: "femme",
      brand: "Prestige Parfum",
      sizes: ["50ml", "100ml"],
      colors: [],
      images: ["/placeholder-perfume-3.jpg"],
      stock: 18,
      featured: true,
      isNew: false,
    },
    {
      name: "Brume Corps Gourmande Vanille",
      description: "Brume parfumée gourmande à la vanille et caramel. Légère et hydratante pour le corps.",
      price: "3200",
      salePrice: null,
      category: "parfums",
      subcategory: "corps",
      brand: "Sweet Body",
      sizes: ["200ml"],
      colors: [],
      images: ["/placeholder-mist-1.jpg"],
      stock: 55,
      featured: false,
      isNew: true,
    },
    {
      name: "Coffret Parfum Découverte",
      description: "Coffret de 5 miniatures de parfums pour découvrir notre collection. Idéal cadeau.",
      price: "4500",
      salePrice: null,
      category: "parfums",
      subcategory: "coffrets",
      brand: "Luxe Fragrance",
      sizes: ["5x10ml"],
      colors: [],
      images: ["/placeholder-giftset-1.jpg"],
      stock: 30,
      featured: false,
      isNew: false,
    },
    {
      name: "Parfum Fleur de Cerisier",
      description: "Eau de parfum délicate aux notes de fleur de cerisier et pivoine. Féminité et fraîcheur.",
      price: "7200",
      salePrice: null,
      category: "parfums",
      subcategory: "femme",
      brand: "Bloom Beauty",
      sizes: ["50ml", "100ml"],
      colors: [],
      images: ["/placeholder-perfume-4.jpg"],
      stock: 35,
      featured: false,
      isNew: true,
    },
    {
      name: "Huile Parfumée Roll-On",
      description: "Huile parfumée en roll-on pour une application précise. Notes florales orientales.",
      price: "2500",
      salePrice: null,
      category: "parfums",
      subcategory: "corps",
      brand: "Oil Essence",
      sizes: ["10ml"],
      colors: [],
      images: ["/placeholder-oil-1.jpg"],
      stock: 65,
      featured: false,
      isNew: false,
    },
  ];

  // Insert products
  for (const product of sampleProducts) {
    await db.insert(products).values(product).onConflictDoNothing();
  }

  // Insert promo codes
  await db.insert(promoCodes).values([
    {
      code: "BIENVENUE10",
      discountType: "percentage",
      discountValue: "10",
      minOrderAmount: "5000",
      maxUses: 100,
      active: true,
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days
    },
    {
      code: "SOLDES20",
      discountType: "percentage",
      discountValue: "20",
      minOrderAmount: "10000",
      maxUses: 50,
      active: true,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
    },
    {
      code: "LIVRAISON",
      discountType: "fixed",
      discountValue: "500",
      minOrderAmount: "3000",
      maxUses: null,
      active: true,
      expiresAt: null,
    },
  ]).onConflictDoNothing();

  console.log("✅ Database seeded successfully!");
  console.log(`📧 Admin email: ${adminEmail}`);
  console.log("🎟️  Promo codes: BIENVENUE10, SOLDES20, LIVRAISON");
}
